### ISSUE TITLE
Why the gradient is divided by sigma?

### ISSUE THREAD

**Issue by MultiPath** [pals-ttic/sjc#6]
Based on the paper equation, it should divide by sigma^2 instead of sigma, right?
https://github.com/pals-ttic/sjc/blob/main/run_sjc.py#L141

<img width="408" alt="image" src="https://user-images.githubusercontent.com/5780274/205466389-0a9cf0a1-e9c5-4786-93b8-4a7a157b4003.png">

**Comment by w-hc** [comment]
I am on my phone. Will expand once I get to laptop. 

If u check out the appendix, or Karras elucidating diffusion, the update is $- \sigma \cdot score$. Also referred to as Twedie’s formula. Although here in case of PAAS, since both $D$ and $x$ are clean images, I’d like to believe you can even not devide anything. It’s really the l2 loss between 2 images.

**Comment by MultiPath** [comment]
I see. Thank you so much for the explanation!
Can I ask another quick question? Does the sigma added on image, and the sigma used to compute score have to be the same? I can imagine the sigma * n added on NeRF output can be annealed as described in the paper, while the other sigma maybe not?
